### ISSUE TITLE
Unable to Detach Device on Travis CI

### ISSUE THREAD

**Issue by danyeaw** [al45tair/dmgbuild#13]
First off, thanks for the awesome library :heart:. [Briefcase](https://github.com/pybee/briefcase) is making use of dmgbuild with the recently released version to automatically create an application package and then build a dmg.

I am trying to use Travis CI to create the dmg. These error messages seem similar to the issue in #10.

```
Building DMG file...
chdiutil: detach: timeout for DiskArbitration expired
hdiutil: detach: drive not detached
Traceback (most recent call last):
  File "setup.py", line 155, in <module>
    "build_mo": {"all_linguas": ",".join(LINGUAS)},
  File "/Users/travis/build/gaphor/gaphor/.venv/lib/python3.7/site-packages/setuptools/__init__.py", line 143, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/travis/build/gaphor/gaphor/.venv/lib/python3.7/site-packages/briefcase/app.py", line 524, in run
    success = self.build_app()
  File "/Users/travis/build/gaphor/gaphor/.venv/lib/python3.7/site-packages/briefcase/macos.py", line 82, in build_app
    'icon': os.path.join(self.resource_dir, '%s.icns' % self.distribution.get_name()),
  File "/Users/travis/build/gaphor/gaphor/.venv/lib/python3.7/site-packages/dmgbuild/core.py", line 556, in build_dmg
    raise DMGError('Unable to detach device cleanly')
dmgbuild.core.DMGError: Unable to detach device cleanly
```

**Comment by danyeaw** [comment]
So I ended up replacing Travis with Azure Pipelines because of this issue. I am not sure if this is really an issue with dmgbuild, or something crazy about how Travis has things configured.
