### ISSUE TITLE
With Python 3.9.4 on macOS 11.2.3, `biplist.InvalidPlistException: module 'plistlib' has no attribute 'Data'`

### ISSUE THREAD

**Issue by twardoch** [al45tair/dmgbuild#35]
With Python 3.9.4 on macOS 11.2.3: 

```
Traceback (most recent call last):
  File "/Users/adam/Library/Python/3.9/bin/dmgbuild", line 36, in <module>
    dmgbuild.build_dmg(args.filename, args.volume_name, args.settings, defines=defines, lookForHiDPI=args.lookForHiDPI)
  File "/Users/adam/Library/Python/3.9/lib/python/site-packages/dmgbuild/core.py", line 235, in build_dmg
    load_settings(settings_file, options)
  File "/Users/adam/Library/Python/3.9/lib/python/site-packages/dmgbuild/core.py", line 90, in load_settings
    exec(compile(fp.read(), filename, 'exec'), settings, settings)
  File "dmgbuild_settings.py", line 78, in <module>
    badge_icon = icon_from_app(application)
  File "dmgbuild_settings.py", line 42, in icon_from_app
    plist = biplist.readPlist(plist_path)
  File "/Users/adam/Library/Python/3.9/lib/python/site-packages/biplist/__init__.py", line 143, in readPlist
    raise InvalidPlistException(e)
biplist.InvalidPlistException: module 'plistlib' has no attribute 'Data'
```

**Comment by PeterPetrik** [comment]
you need to update your dmgsettings.py

```
# Before Python 3.4, use biplist; afterwards, use plistlib
if sys.version_info < (3, 4):
    import biplist
    def read_plist(path):
        return biplist.readPlist(path)
else:
    import plistlib
    def read_plist(path):
        with open(path, 'rb') as f:
            return plistlib.load(f)
```

**Comment by al45tair** [comment]
@twardoch What @PeterPetrik said.
