### ISSUE TITLE
NameError: name 'dmgbuild' is not defined in 1.5.0

### ISSUE THREAD

**Issue by hoffie** [al45tair/dmgbuild#40]
I'm seeing this in [our CI](https://github.com/hoffie/jamulus/runs/2709826916?check_suite_focus=true#step:6:1329) (we use `dmgbuild` in the jamulussoftware/jamulus project):
```
Traceback (most recent call last):
  File "/Users/runner/Library/Python/2.7/bin/dmgbuild", line 11, in <module>
    load_entry_point('dmgbuild==1.5.0', 'console_scripts', 'dmgbuild')()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/runner/Library/Python/2.7/lib/python/site-packages/dmgbuild/__main__.py", line 37, in <module>
    dmgbuild.build_dmg(args.filename, args.volume_name, args.settings, defines=defines, lookForHiDPI=args.lookForHiDPI)
NameError: name 'dmgbuild' is not defined
Error: Process completed with exit code 1.
```

This happens with both python2.7 and python3.

I guess at least this place:
https://github.com/al45tair/dmgbuild/blob/bfeb0a235647e777069cbaf4a8b6365f09f1b96a/dmgbuild/__main__.py#L37

would have to be adapted?

```diff
- dmgbuild.build_dmg(args.filename, args.volume_name, args.settings, defines=defines, lookForHiDPI=args.lookForHiDPI)
+ build_dmg(args.filename, args.volume_name, args.settings, defines=defines, lookForHiDPI=args.lookForHiDPI) 
```

The following commit looks related:
https://github.com/al45tair/dmgbuild/commit/f84453a0f7cff92890cdaee5968dad321b6eddff

I'm not sure if this is the only place. Also, I'm not planning to raise a PR because I cannot test this due to lack of access to a Mac. :)

We are going back to 1.4.2 for now.

**Comment by al45tair** [comment]
This should now be fixed. Thanks for raising the issue.
